package com.example.empsched.schedulingservice.service;

import com.example.empsched.schedulingservice.entity.Schedule;
import com.example.empsched.schedulingservice.entity.Shift;
import org.springframework.stereotype.Service;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

@Service
public class ShiftGeneratorService {

    // Define standard shift times (Could also come from DB config)
    private static final LocalTime MORNING_START = LocalTime.of(8, 0);
    private static final LocalTime MORNING_END = LocalTime.of(16, 0);

    private static final LocalTime EVENING_START = LocalTime.of(16, 0);
    private static final LocalTime EVENING_END = LocalTime.of(0, 0); // Midnight

    /**
     * Generates empty shift slots for the entire duration of the schedule.
     */
    public List<Shift> generateShiftsFor(Schedule schedule) {
        List<Shift> newShifts = new ArrayList<>();

        LocalDate currentDate = schedule.getStartDate();
        LocalDate endDate = schedule.getEndDate();

        // Loop through every day of the schedule
        while (!currentDate.isAfter(endDate)) {

            // --- LOGIC: Define what shifts are needed per day ---

            // Example: Every day needs 2 "Nurses" in the morning
            newShifts.add(createShift(schedule, currentDate, MORNING_START, MORNING_END, "Nurse"));
            newShifts.add(createShift(schedule, currentDate, MORNING_START, MORNING_END, "Nurse"));

            // Example: Every day needs 1 "Doctor" in the morning
            newShifts.add(createShift(schedule, currentDate, MORNING_START, MORNING_END, "Doctor"));

            // Example: Every day needs 2 "Nurses" in the evening
            newShifts.add(createShift(schedule, currentDate, EVENING_START, EVENING_END, "Nurse"));
            newShifts.add(createShift(schedule, currentDate, EVENING_START, EVENING_END, "Nurse"));

            // Move to next day
            currentDate = currentDate.plusDays(1);
        }

        return newShifts;
    }

    private Shift createShift(Schedule schedule, LocalDate date, LocalTime start, LocalTime end, String skill) {
        Shift shift = new Shift();
        // ID is auto-generated by DB/Hibernate upon save,
        // OR you can generate it here if you want: shift.setId(UUID.randomUUID());

        shift.setSchedule(schedule); // Link to parent
        shift.setRequiredSkill(skill);
        shift.setStartTime(LocalDateTime.of(date, start));

        // Handle overnight shifts (if end is before start, it's next day)
        if (end.isBefore(start)) {
            shift.setEndTime(LocalDateTime.of(date.plusDays(1), end));
        } else {
            shift.setEndTime(LocalDateTime.of(date, end));
        }

        shift.setAssignedEmployee(null); // CRITICAL: This tells Timefold it's an open slot
        return shift;
    }
}
