server:
  port: ${GATEWAY_APP_PORT}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    eureka-service-url-poll-interval-seconds: 60
  instance:
    prefer-ip-address: true
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}