services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_MAPPED_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - empsched-backend-network

  elasticsearch:
    image: elasticsearch:9.0.1
    container_name: elasticsearch
    restart: always
    environment:
      - ELASTIC_PASSWORD=changeme
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_MAPPER_PORT}:${ELASTICSEARCH_PORT}"
    networks:
      - empsched-backend-network

  logstash:
    image: logstash:9.0.1
    container_name: logstash
    restart: always
    environment:
      - 'LS_JAVA_OPTS=-Xms256m -Xmx256m'
    volumes:
      - ../docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ../docker/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "${LOGSTASH_MAPPED_PORT}:${LOGSTASH_PORT}"
    depends_on:
      - elasticsearch
    networks:
      - empsched-backend-network

  kibana:
    image: kibana:9.0.1
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_URL}
      - 'NODE_OPTIONS=--max-old-space-size=512'
    ports:
      - "${KIBANA_MAPPED_PORT}:${KIBANA_PORT}"
    depends_on:
      - elasticsearch
    networks:
      - empsched-backend-network

  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: empsched
      RABBITMQ_DEFAULT_PASS: empsched
    ports:
      - "${RABBITMQ_MAPPED_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_MAPPED_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    networks:
      - empsched-backend-network

  prometheus:
    image: prom/prometheus:v3.4.0
    restart: always
    container_name: prometheus
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ../docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_MAPPED_PORT}:${PROMETHEUS_PORT}"
    networks:
      - empsched-backend-network

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    ports:
      - "${GRAFANA_MAPPED_PORT}:${GRAFANA_PORT}"
    networks:
      - empsched-backend-network

  zipkin:
    image: openzipkin/zipkin:3.5
    container_name: zipkin
    restart: always
    ports:
      - "${ZIPKIN_MAPPED_PORT}:${ZIPKIN_PORT}"
    networks:
      - empsched-backend-network

volumes:
  db_data:
  es_data:

networks:
  empsched-backend-network:
    external: true