server:
  port: ${AUTH_APP_PORT}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  threads:
    virtual:
      enabled: true
  application:
    name: auth-service
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: ${DATASOURCE_URL}${DATASOURCE_AUTH_DATABASE}
    username: ${DATASOURCE_AUTH_USERNAME}
    password: ${DATASOURCE_AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        observation-enabled: true
    template:
      observation-enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
jwt:
  expiration:
    time: 3600
  public:
    key: classpath:certs/public.pem
  private:
    key: classpath:certs/private.pem
