server:
  port: 9001
spring:
  application:
    name: auth-service
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/empshed_auth
    username: empshed
    password: empshed
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: empsched
    password: empsched
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9050/eureka/
  instance:
    prefer-ip-address: true