server:
  port: 9001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/empshed_auth
    username: empshed
    password: empshed
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9050/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans