server:
  port: ${EUREKA_APP_PORT}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}