global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'eureka'
    eureka_sd_configs:
      - server: 'http://host.docker.internal:9050/eureka'
    relabel_configs:
      - source_labels: [__meta_eureka_app_instance_metadata_prometheus_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_eureka_app_instance_metadata_prometheus_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)